package com.squad.be.dto.enums;

public enum Fields {
    WINS,LOSSES,LEAGUE_POINTS,RANK,TIER,cluster,USERNAME,EMAIL,ACCOUNT_NAME,ACCOUNT_ID,ACCOUNT_LEVEL,SCHEDULE_TIME_START,SCHEDULE_TIME_END,ROLE
}
